- name: "{{ messengers.protonmail_bridge.installed | ternary('Install', 'Remove') }} Protonmail Bridge flatpak."
  community.general.flatpak:
    name: ch.protonmail.protonmail-bridge
    state: "{{ messengers.protonmail_bridge.installed | ternary('present', 'absent') }}"
    method: "{{ flatpak.method }}"
  become: "{{ flatpak.method == 'system' }}"
  notify:
    - Cleanup flatpaks.
