- name: "{{ messengers.signal.installed | ternary('Install', 'Remove') }} Signal flatpak."
  community.general.flatpak:
    name: org.signal.Signal
    state: "{{ messengers.signal.installed | ternary('present', 'absent') }}"
  become: true
  become_user: root
  notify:
    - Cleanup flatpaks.
