- name: "{{ messengers.teams.installed | ternary('Install', 'Remove') }} Teams flatpak."
  community.general.flatpak:
    name: com.microsoft.Teams
    state: "{{ messengers.teams.installed | ternary('present', 'absent') }}"
  become: true
  become_user: root
  notify:
    - Cleanup flatpaks.
