- name: "{{ messengers.teams.installed | ternary('Install', 'Remove') }} Teams flatpak."
  community.general.flatpak:
    name: com.microsoft.Teams
    state: "{{ messengers.teams.installed | ternary('present', 'absent') }}"
    method: "{{ flatpak.method }}"
  become: "{{ flatpak.method == 'system' }}"
  notify:
    - Cleanup flatpaks.
