- name: "{{ messengers.telegram.installed | ternary('Install', 'Remove') }} Telegram flatpak."
  community.general.flatpak:
    name: org.telegram.desktop
    state: "{{ messengers.telegram.installed | ternary('present', 'absent') }}"
  become: true
  become_user: root
  notify:
    - Cleanup flatpaks.
