- name: "{{ messengers.threema.installed | ternary('Install', 'Remove') }} Thunderbird package."
  ansible.builtin.package:
    name: thunderbird
    state: "{{ messengers.threema.installed | ternary('present', 'absent') }}"
  become: true
  become_user: root
