- name: "{{ messengers.whatsapp.installed | ternary('Install', 'Remove') }} WhatsApp flatpak."
  community.general.flatpak:
    name: com.github.eneshecan.WhatsAppForLinux
    state: "{{ messengers.whatsapp.installed | ternary('present', 'absent') }}"
  become: true
  become_user: root
  notify:
    - Cleanup flatpaks.
