- name: "{{ multimedia.digikam.installed | ternary('Install', 'Remove') }} Digikam flatpak."
  community.general.flatpak:
    name: org.kde.digikam
    state: "{{ multimedia.digikam.installed | ternary('present', 'absent') }}"
    method: "{{ flatpak.method }}"
  become: "{{ flatpak.method == 'system' }}"
  notify:
    - Cleanup flatpaks.
