- name: "{{ multimedia.gimp.installed | ternary('Install', 'Remove') }} Gimp flatpak."
  community.general.flatpak:
    name: org.gimp.GIMP
    state: "{{ multimedia.gimp.installed | ternary('present', 'absent') }}"
    method: "{{ flatpak.method }}"
  become: "{{ flatpak.method == 'system' }}"
  notify:
    - Cleanup flatpaks.
