- name: "{{ multimedia.spotify.installed | ternary('Install', 'Remove') }} Spotify flatpak."
  community.general.flatpak:
    name: com.spotify.Client
    state: "{{ multimedia.spotify.installed | ternary('present', 'absent') }}"
    method: "{{ flatpak.method }}"
  become: "{{ flatpak.method == 'system' }}"
  notify:
    - Cleanup flatpaks.
