- name: "{{ multimedia.vlc.installed | ternary('Install', 'Remove') }} VLC flatpak."
  community.general.flatpak:
    name: org.videolan.VLC
    state: "{{ multimedia.vlc.installed | ternary('present', 'absent') }}"
    method: "{{ flatpak.method }}"
  become: "{{ flatpak.method == 'system' }}"
  notify:
    - Cleanup flatpaks.
