- name: "{{ multimedia.vlc.installed | ternary('Install', 'Remove') }} VLC cask."
  community.general.homebrew_cask:
    name: homebrew/cask/vlc
    state: "{{ multimedia.vlc.installed | ternary('present', 'absent') }}"
  become: true
