- name: Load cli_tools tasks.
  ansible.builtin.include_tasks:
    file: "{{ tasks }}"
  with_first_found:
    - "tasks-{{ ansible_distribution }}.yml"
    - "tasks-{{ ansible_system }}.yml"
  loop_control:
    loop_var: tasks
