- name: Install packages.
  ansible.builtin.package:
    name: "{{ tool.key }}"
    state: "{{ tool.value['installed'] | ternary('present', 'absent') }}"
  become: true
  loop: "{{ cli_tools | dict2items }}"
  loop_control:
    loop_var: tool
